App\Entity\Location: 

  properties:
    latitude:
      - Range: 
                min: -90
                max: 90
      - NotBlank: ~
    longitude:
      - Range: 
                min: -90
                max: 90
      - NotBlank: ~
    city:
      - NotBlank: ~
    country:
      - NotBlank: ~